const fuzz = require('fuzzball');
const Discord = require('discord.js');
const client = new Discord.Client();
const config = require('./config.json');
const pokedexToken = config.pokedexToken;

const names = ["Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", "Squirtle", "Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree", "Weedle", "Kakuna", "Beedrill", "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate", "Spearow", "Fearow", "Ekans", "Arbok", "Pikachu", "Raichu", "Sandshrew", "Sandslash", "Nidoran♀", "Nidorina", "Nidoqueen", "Nidoran♂", "Nidorino", "Nidoking", "Clefairy", "Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff", "Zubat", "Golbat", "Oddish", "Gloom", "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth", "Diglett", "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck", "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath", "Abra", "Kadabra", "Alakazam", "Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool", "Tentacruel", "Geodude", "Graveler", "Golem", "Ponyta", "Rapidash", "Slowpoke", "Slowbro", "Magnemite", "Magneton", "Farfetch’d", "Doduo", "Dodrio", "Seel", "Dewgong", "Grimer", "Muk", "Shellder", "Cloyster", "Gastly", "Haunter", "Gengar", "Onix", "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak", "Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Chansey", "Tangela", "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu", "Starmie", "Mr. Mime", "Scyther", "Jynx", "Electabuzz", "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados", "Lapras", "Ditto", "Eevee", "Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto", "Kabutops", "Aerodactyl", "Snorlax", "Articuno", "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew", "Chikorita", "Bayleef", "Meganium", "Cyndaquil", "Quilava", "Typhlosion", "Totodile", "Croconaw", "Feraligatr", "Sentret", "Furret", "Hoothoot", "Noctowl", "Ledyba", "Ledian", "Spinarak", "Ariados", "Crobat", "Chinchou", "Lanturn", "Pichu", "Cleffa", "Igglybuff", "Togepi", "Togetic", "Natu", "Xatu", "Mareep", "Flaaffy", "Ampharos", "Bellossom", "Marill", "Azumarill", "Sudowoodo", "Politoed", "Hoppip", "Skiploom", "Jumpluff", "Aipom", "Sunkern", "Sunflora", "Yanma", "Wooper", "Quagsire", "Espeon", "Umbreon", "Murkrow", "Slowking", "Misdreavus", "Unown", "Wobbuffet", "Girafarig", "Pineco", "Forretress", "Dunsparce", "Gligar", "Steelix", "Snubbull", "Granbull", "Qwilfish", "Scizor", "Shuckle", "Heracross", "Sneasel", "Teddiursa", "Ursaring", "Slugma", "Magcargo", "Swinub", "Piloswine", "Corsola", "Remoraid", "Octillery", "Delibird", "Mantine", "Skarmory", "Houndour", "Houndoom", "Kingdra", "Phanpy", "Donphan", "Porygon2", "Stantler", "Smeargle", "Tyrogue", "Hitmontop", "Smoochum", "Elekid", "Magby", "Miltank", "Blissey", "Raikou", "Entei", "Suicune", "Larvitar", "Pupitar", "Tyranitar", "Lugia", "Ho-Oh", "Celebi", "Treecko", "Grovyle", "Sceptile", "Torchic", "Combusken", "Blaziken", "Mudkip", "Marshtomp", "Swampert", "Poochyena", "Mightyena", "Zigzagoon", "Linoone", "Wurmple", "Silcoon", "Beautifly", "Cascoon", "Dustox", "Lotad", "Lombre", "Ludicolo", "Seedot", "Nuzleaf", "Shiftry", "Taillow", "Swellow", "Wingull", "Pelipper", "Ralts", "Kirlia", "Gardevoir", "Surskit", "Masquerain", "Shroomish", "Breloom", "Slakoth", "Vigoroth", "Slaking", "Nincada", "Ninjask", "Shedinja", "Whismur", "Loudred", "Exploud", "Makuhita", "Hariyama", "Azurill", "Nosepass", "Skitty", "Delcatty", "Sableye", "Mawile", "Aron", "Lairon", "Aggron", "Meditite", "Medicham", "Electrike", "Manectric", "Plusle", "Minun", "Volbeat", "Illumise", "Roselia", "Gulpin", "Swalot", "Carvanha", "Sharpedo", "Wailmer", "Wailord", "Numel", "Camerupt", "Torkoal", "Spoink", "Grumpig", "Spinda", "Trapinch", "Vibrava", "Flygon", "Cacnea", "Cacturne", "Swablu", "Altaria", "Zangoose", "Seviper", "Lunatone", "Solrock", "Barboach", "Whiscash", "Corphish", "Crawdaunt", "Baltoy", "Claydol", "Lileep", "Cradily", "Anorith", "Armaldo", "Feebas", "Milotic", "Castform", "Kecleon", "Shuppet", "Banette", "Duskull", "Dusclops", "Tropius", "Chimecho", "Absol", "Wynaut", "Snorunt", "Glalie", "Spheal", "Sealeo", "Walrein", "Clamperl", "Huntail", "Gorebyss", "Relicanth", "Luvdisc", "Bagon", "Shelgon", "Salamence", "Beldum", "Metang", "Metagross", "Regirock", "Regice", "Registeel", "Latias", "Latios", "Kyogre", "Groudon", "Rayquaza", "Jirachi", "Deoxys", "Turtwig", "Grotle", "Torterra", "Chimchar", "Monferno", "Infernape", "Piplup", "Prinplup", "Empoleon", "Starly", "Staravia", "Staraptor", "Bidoof", "Bibarel", "Kricketot", "Kricketune", "Shinx", "Luxio", "Luxray", "Budew", "Roserade", "Cranidos", "Rampardos", "Shieldon", "Bastiodon", "Burmy", "Wormadam", "Mothim", "Combee", "<@!260804864379060224>", "<@302881285750128651>", "Buizel", "Floatzel", "Cherubi", "Cherrim", "Shellos", "Gastrodon", "Ambipom", "Drifloon", "Drifblim", "Buneary", "Lopunny", "Mismagius", "Honchkrow", "Glameow", "Purugly", "Chingling", "Stunky", "Skuntank", "Bronzor", "Bronzong", "Bonsly", "Mime Jr.", "Happiny", "Chatot", "Spiritomb", "Gible", "Gabite", "Garchomp", "Munchlax", "Riolu", "Lucario", "Hippopotas", "Hippowdon", "Skorupi", "Drapion", "Croagunk", "Toxicroak", "Carnivine", "Finneon", "Lumineon", "Mantyke", "Snover", "Abomasnow", "Weavile", "Magnezone", "Lickilicky", "Rhyperior", "Tangrowth", "Electivire", "Magmortar", "Togekiss", "Yanmega", "Leafeon", "Glaceon", "Gliscor", "Mamoswine", "Porygon-Z", "Gallade", "Probopass", "Dusknoir", "Froslass", "Rotom", "Uxie", "Mesprit", "Azelf", "Dialga", "Palkia", "Heatran", "Regigigas", "Giratina", "Cresselia", "Phione", "Manaphy", "Darkrai", "Shaymin", "Arceus", "Victini", "Snivy", "Servine", "Serperior", "Tepig", "Pignite", "Emboar", "Oshawott", "Dewott", "Samurott", "Patrat", "Watchog", "Lillipup", "Herdier", "Stoutland", "Purrloin", "Liepard", "Pansage", "Simisage", "Pansear", "Simisear", "Panpour", "Simipour", "Munna", "Musharna", "Pidove", "Tranquill", "Unfezant", "Blitzle", "Zebstrika", "Roggenrola", "Boldore", "Gigalith", "Woobat", "Swoobat", "Drilbur", "Excadrill", "Audino", "Timburr", "Gurdurr", "Conkeldurr", "Tympole", "Palpitoad", "Seismitoad", "Throh", "Sawk", "Sewaddle", "Swadloon", "Leavanny", "Venipede", "Whirlipede", "Scolipede", "Cottonee", "Whimsicott", "Petilil", "Lilligant", "Basculin", "Sandile", "Krokorok", "Krookodile", "Darumaka", "Darmanitan", "Maractus", "Dwebble", "Crustle", "Scraggy", "Scrafty", "Sigilyph", "Yamask", "Cofagrigus", "Tirtouga", "Carracosta", "Archen", "Archeops", "Trubbish", "Garbodor", "Zorua", "Zoroark", "Minccino", "Cinccino", "Gothita", "Gothorita", "Gothitelle", "Solosis", "Duosion", "Reuniclus", "Ducklett", "Swanna", "Vanillite", "Vanillish", "Vanilluxe", "Deerling", "Sawsbuck", "Emolga", "Karrablast", "Escavalier", "Foongus", "Amoonguss", "Frillish", "Jellicent", "Alomomola", "Joltik", "Galvantula", "Ferroseed", "Ferrothorn", "Klink", "Klang", "Klinklang", "Tynamo", "Eelektrik", "Eelektross", "Elgyem", "Beheeyem", "Litwick", "MadPoGoTracker", "Chandelure", "Axew", "Fraxure", "Haxorus", "Cubchoo", "Beartic", "Cryogonal", "Shelmet", "Accelgor", "Stunfisk", "Mienfoo", "Mienshao", "Druddigon", "Golett", "Golurk", "Pawniard", "Bisharp", "Bouffalant", "Rufflet", "Braviary", "Vullaby", "Mandibuzz", "Heatmor", "Durant", "Deino", "Zweilous", "Hydreigon", "Larvesta", "Volcarona", "Cobalion", "Terrakion", "Virizion", "Tornadus", "Thundurus", "Reshiram", "Zekrom ", "Landorus", "Kyurem", "Keldeo", "Meloetta", "Genesect", "Chespin", "Quilladin", "Chesnaught", "Fennekin", "Braixen", "Delphox", "Froakie", "Frogadier", "Greninja", "Bunnelby", "Diggersby", "Fletchling", "Fletchinder", "Talonflame", "Scatterbug", "Spewpa", "Vivillon", "Litleo", "Pyroar", "Flabebe", "Floette", "Florges", "Skiddo", "Gogoat", "Pancham", "Pangoro", "Furfrou", "Espurr", "Meowstic", "Honedge", "Doublade", "Aegislash", "Spritzee", "Aromatisse", "Swirlix", "Slurpuff", "Inkay", "Malamar", "Binacle", "Barbaracle", "Skrelp", "Dragalge", "Clauncher", "Clawitzer", "Helioptile", "Heliolisk", "Tyrunt", "Tyrantrum", "Amaura", "Aurorus", "Sylveon", "Hawlucha", "Dedenne", "Carbink", "Goomy", "Sliggoo", "Goodra", "Klefki", "Phantump", "Trevenant", "Pumpkaboo", "Gourgeist", "Bergmite", "Avalugg", "Noibat", "Noivern", "Xerneas", "Yveltal", "Zygarde", "Diancie", "Hoopa", "Volcanion", "Rowlet", "Dartrix", "Decidueye", "Litten", "Torracat", "Incineroar", "Popplio", "Brionne", "Primarina", "Pikipek", "Trumbeak", "Toucannon", "Yungoos", "Gumshoos", "Grubbin", "Charjabug", "Vikavolt", "Crabrawler", "Crabominable", "Oricorio", "Cutiefly", "Ribombee", "Rockruff", "Lycanroc", "Wishiwashi", "Mareanie", "Toxapex", "Mudbray", "Mudsdale", "Dewpider", "Araquanid", "Fomantis", "Lurantis", "Morelull", "Shiinotic", "Salandit", "Salazzle", "Stufful", "Bewear", "Bounsweet", "Steenee", "Tsareena", "Comfey", "Oranguru", "Passimian", "Wimpod", "Golisopod", "Sandygast", "Palossand", "Pyukumuku", "Type: Null", "Silvally", "Minior", "Komala", "Turtonator", "Togedemaru", "Mimikyu", "Bruxish", "Drampa", "Dhelmise", "Jangmo-o", "Hakamo-o", "Kommo-o", "Tapu Koko", "Tapu Lele", "Tapu Bulu", "Tapu Fini", "Cosmog", "Cosmoem", "Solgaleo", "Lunala", "Nihilego", "Buzzwole", "Pheromosa", "Xurkitree", "Celesteela", "Kartana", "Guzzlord", "Necrozma", "Magearna", "Marshadow"]

/**
 * WHO'S THAT POKEMON!?
 * Function to try to guess which pokemon the user is trying to type in
 * @param poke - the user's input.  Can be #111, 111, or text
 * @returns the ID of the pokemon they typed in
 */
function interpretPoke(poke) {
    console.log("==INTERPRET POKEMON:  " + poke + "==")
    let pokeID = 0;

    //Add shortcut names here.
    switch (poke) {
        case 'ttar':
            poke = 'tyranitar';
            break;
		case 'trex':
            poke = 'tyranitar';
            break;
        case 'zap':
            poke = 'zapdos';
            break
		case '@dom':
            poke = '<@302881285750128651>';
            break;
		case 'dom':
            poke = '<@302881285750128651>';
            break;
        case 'gary':
            poke = 'gyarados';
            break;
        case 'doompupper':
            poke = 'houndour';
            break;
        case 'doomdoggo':
            poke = 'houndoom';
            break;
    }

    if (parseInt(poke) > 0 && parseInt(poke) <= names.length) {
        console.log("==\twas a number that was between 1 and " + names.length)
        pokeID = parseInt(poke);
    } else {
        console.log("==\tBegin fuzzy search")
        let options = {
            scorer: fuzz.token_set_ratio
        };
        let match = fuzz.extract(poke, names, options)[0]
        console.log("==\tBest match is: " + match)
        if (match[1] >= 50) { // pretty sure we figured it out
            console.log("==\tHigh Enough Score to say this is probably it.")
            pokeID = match[2] + 1; //index, but Pokemon start at a non-zero index (Bulbasaur = 1, not 0)
        } else {
            console.log("&&\tNo idea.  returning what we started with.")
            pokeID = poke;
        }
    }
    return pokeID;
}



client.on('ready', () => {
    console.log('I am ready!');
    client.user.setGame('?help | Usage info');
});

client.on('message', message => {
    if (message.content.toLowerCase() === 'ping') {
        message.reply('pong');
    }
});

//
// Pokemon typing logic
//
class PokeType {
    constructor(author, color, supereffective, noteffective, resistant, weak) {
        this.emb = new Discord.RichEmbed()
            .setAuthor(author)
            .setColor(color)
            .addField("Super Effective Against:", supereffective)
            .addField("Not Very Effective Against:", noteffective)
            .addField("Resistant to:", resistant)
            .addField("Weak to:", weak)
    }
}

//
// Weather typing logic
//

class WeatherType {
    constructor(author, boostedType) {
        this.emb = new Discord.RichEmbed()
            .setAuthor(author)
            .addField("Boosted Types:", boostedType)
    }
}

//
// Pokemon logic
//
class Pokemon {
    constructor(pokeID, color, types, raidLevel, weatherBoost, topCounters, weakTo, resistantTo, moveSetGrades, lvl15CP, lvl20CP, lvl25CP, lvl30CP, lvl35CP, lvl40CP) {
        this.emb = new Discord.RichEmbed()
            .setAuthor(`#${pokeID} ${names[pokeID-1]}`, `https:\/\/raw.githubusercontent.com/gladiator10864/PokeAlarm/master/icons/${pokeID}.png`)
            .setColor(color)
            .setThumbnail(`https:\/\/raw.githubusercontent.com/kvangent/gladiator10864/master/icons/${pokeID}.png`)
        if (raidLevel > 0 || raidLevel === "EX Invite Only") {
            this.emb.setDescription("**Type: **" + types + "\nRaid Level: " + raidLevel + "\nBoosted In: " + weatherBoost)
        } else {
            this.emb.setDescription("**Type: **" + types + "\nBoosted In: " + weatherBoost)
        }
        this.emb.addField("Best Counters:", topCounters)
            .addField("Weak to:", weakTo)
            .addField("Resistant to:", resistantTo)
            .addField("Best Movesets (%, DMG, Moveset): ", moveSetGrades)
            .addField("Perfect CP's: ", "Lvl 15 = " + lvl15CP + "\nLvl 20 =  " + lvl20CP + "\nLvl 25 =  " + lvl25CP + "\nLvl 30 = " + lvl30CP + "\nLvl 35 = " + lvl35CP + "\nLvl 40 = " + lvl40CP + "\n[More Info](https:\/\/db.pokemongohub.net/pokemon/" + pokeID + ")");
    }
}

// Colors (by type)
let colors = {
    normal: 0x80847d,
    fighting: 0xa50000,
    flying: 0x708ee0,
    poison: 0xe064e0,
    ground: 0x966622,
    rock: 0xba9560,
    bug: 0x82f722,
    ghost: 0x7526d6,
    steel: 0x005791,
    fire: 0xff7b00,
    water: 0x0902e5,
    grass: 0x017208,
    electric: 0xfff600,
    psychic: 0xff494c,
    ice: 0x509fd8,
    dark: 0x252728,
    dragon: 0x036fa5,
    fairy: 0xf9b6ee
};

// Type objects
let types = {
    normal: new PokeType("Normal Type", colors.normal, "None", "Rock, Steel, Ghost (x2)", "Ghost(x2)", "Fighting"),
    fighting: new PokeType("Fighting Type", colors.fighting, "Dark, Ice, Normal, Rock, Steel", "Bug, Fairy, Flying, Poison, Psychic, Ghost (x2)", "Bug, Dark, Rock", "Fairy, Flying, Psychic"),
    flying: new PokeType("Flying Type", colors.flying, "Bug, Fighting, Grass", "Electric, Rock, Steel", "Bug, Fighting, Grass, Ground (x2)", "Electric, Ice, Rock"),
    poison: new PokeType("Poison Type", colors.poison, "Grass, Fairy", "Ghost, Ground, Poison, Rock, Steel (x2)", "Bug, Fairy, Fighting, Grass, Poison", "Ground, Psychic"),
    ground: new PokeType("Ground Type", colors.ground, "Electric, Fire, Poison, Rock, Steel", "Bug, Grass, Flying (x2)", "Poison, Rock, Electric (x2)", "Grass, Ice, Water"),
    rock: new PokeType("Rock Type", colors.rock, "Bug, Flying, Fire, Ice", "Fighting, Ground, Steel", "Fire, Flying, Normal, Poison", "Fighting, Grass, Ground, Steel, Water"),
    bug: new PokeType("Bug Type", colors.bug, "Psychic, Grass, Dark", "Fighting, Fire, Flying, Ghost, Poison, Steel, Fairy", "Fighting, Grass, Ground", "Fire, Flying, Rock"),
    ghost: new PokeType("Ghost Type", colors.ghost, "Ghost, Psychic", "Dark, Normal (x2)", "Bug, Poison, Normal (x2), Fighting (x2)", "Ghost, Dark"),
    steel: new PokeType("Steel Type", colors.steel, "Fairy, Ice, Rock", "Electric, Fire, Steel, Water", "Bug, Dragon, Fairy, Flying, Grass, Ice, Normal, Psychic, Rock, Steel, Poison (x2)", "Fighting, Fire, Ground"),
    fire: new PokeType("Fire Type", colors.fire, "Bug, Grass, Ice, Steel", "Dragon, Fire, Rock, Water", "Bug, Fairy, Fire, Grass, Ice, Steel", "Ground, Rock, Water"),
    water: new PokeType("Water Type", colors.water, "Fire, Ground, Rock", "Dragon, Grass, Water", "Fire, Ice, Steel, Water", "Electric, Grass"),
    grass: new PokeType("Grass Type", colors.grass, "Ground, Rock, Water", "Bug, Dragon, Fire, Flying, Grass, Poison, Steel", "Electric, Grass, Ground, Water", "Bug, Fire, Flying, Ice, Poison"),
    electric: new PokeType("Electric Type", colors.electric, "Flying, Water", "Dragon, Electric, Grass, Ground (x2)", "Electric, Flying, Steel", "Ground"),
    psychic: new PokeType("Psychic Type", colors.psychic, "Fighting, Poison", "Psychic, Steel, Dark (x2)", "Fighting, Psychic", "Bug, Dark, Ghost"),
    ice: new PokeType("Ice Type", colors.ice, "Dragon, Flying, Grass, Ground", "Fire, Ice, Steel, Water", "Ice", "Fighting, Fire, Rock, Steel"),
    dark: new PokeType("Dark Type", colors.dark, "Ghost, Psychic", "Dark, Fighting, Fairy", "Dark, Ghost, Psychic (x2)", "Bug, Fighting, Fairy"),
    dragon: new PokeType("Dragon Type", colors.dragon, "Dragon", "Steel, Fairy (x2)", "Electric, Fire, Grass, Water", "Dragon, Ice, Fairy"),
    fairy: new PokeType("Fairy Type", colors.fairy, "Dark, Dragon, Fighting", "Fire, Poison, Steel", "Bug, Dark, Fighting, Dragon (x2)", "Poison, Steel")
}

// Weather objects
let boostedType = {
    sunny: new WeatherType("Sunny / Clear", "Grass, Fire, Ground"),
    clear: new WeatherType("Sunny / Clear", "Grass, Fire, Ground"),
    rainy: new WeatherType("Rainy", "Water, Electric, Bug"),
    "partly cloudy": new WeatherType("Partly Cloudy", "Normal, Rock"),
    cloudy: new WeatherType("Cloudy", "Fairy, Fighting, Poison"),
    windy: new WeatherType("Windy", "Flying, Dragon, Psychic"),
    snow: new WeatherType("Snow", "Ice, Steel"),
    fog: new WeatherType("Fog", "Dark, Ghost"),
    foggy: new WeatherType("Fog", "Dark, Ghost")
}

// Pokemon objects
let pokemon = {
    1: new Pokemon(1, colors.grass, 'Grass / Poison', 0, 'Clear / Sunny, Cloudy', '1. Entei | Fire Fang / Overheat\n2. Moltres | Fire Sping / Overheat\n3. Rayquaza | Air Slash / Aerial Ace\n4. Ho-oh | Extrasensory / Fire Blast\n5. Mewtwo | Psycho Cut / Psychic', 'Fire, Flying, Ice, Psychic', 'Electric, Fairy, Fighting, Grass (x2), Water', '100%, 299, Vine Whip / Power Whip\n95.5%, 286, Wine Whip / Seed Bomb\n93.6%, 280, Tackle / Power Whip\n93.3%, 279, Vine Whip / Sludge Bomb\n89.2%, 267, Tackle / Seed Bomb\n87.0%, 260, Tackle / Sludge Bomb', 420, 560, 701, 841, 911, 981),
    2: new Pokemon(2, 0x017208, 'Grass/Poison', 4, 0, 'Mewtwo | (Confusion, Psycho Cut)/(Psychic, Shadow Ball)\nMoltres | Fire Spin/Overheat\nLugia | Extrasensory/(Sky Attack, Future Sight)', 'Fire, Flying, Ice, Psychic', 'Grass(x2), Electric, Fairy, Fight, Water', '**A/D** | Vine Whip/Solar Beam\n**A/B** | Razor Leaf/Solar Beam\n**B/D** | Vine Whip/Petal Blizzard\n**B/C** | Vine Whip/Sludge Bomb\n**B/B** | Razor Leaf/Petal Blizzard\n**B/A** | Razor Leaf/Sludge Bomb', 0, 886, 0, 0, 0, 0),
    3: new Pokemon(3, 0x017208, 'Grass/Poison', 4, 0, 'Mewtwo | (Confusion, Psycho Cut)/(Psychic, Shadow Ball)\nMoltres | Fire Spin/Overheat\nLugia | Extrasensory/(Sky Attack, Future Sight)', 'Fire, Flying, Ice, Psychic', 'Grass(x2), Electric, Fairy, Fight, Water', '**A/D** | Vine Whip/Solar Beam\n**A/B** | Razor Leaf/Solar Beam\n**B/D** | Vine Whip/Petal Blizzard\n**B/C** | Vine Whip/Sludge Bomb\n**B/B** | Razor Leaf/Petal Blizzard\n**B/A** | Razor Leaf/Sludge Bomb', 0, 1467, 0, 0, 0, 0),
    4: undefined,
    5: new Pokemon(5, 0xff7b00, 'Fire', 4, 0, 'Golem | (Rock Throw, Mud Slap, Mud Shot)/(Stone Edge, Rock Blast)', 'Electric, Rock (x2), Water', 'Bug (x2), Fire, Grass (x2), Fairy, Ground, Steel, Fighting', '**A / B** |  Fire Spin / Overheat\n**A- / B-** | Air Slash / Overheat\n**A- / D** | Wing Attack\* / Overheat\n**A- / C** - Ember\* / Overheat', 0, 1535, 0, 0, 0, 0),
    6: new Pokemon(6, 0xff7b00, 'Fire/Flying', 4, 0, 'Golem | (Rock Throw, Mud Slap, Mud Shot)/(Stone Edge, Rock Blast)', 'Electric, Rock (x2), Water', 'Bug (x2), Fire, Grass (x2), Fairy, Ground, Steel, Fighting', '**A / B** |  Fire Spin / Overheat\n**A- / B-** | Air Slash / Overheat\n**A- / D** | Wing Attack\* / Overheat\n**A- / C** - Ember\* / Overheat', 0, 1535, 0, 0, 0, 0),
    7: undefined,
    8: new Pokemon(8, 0x0902e5, 'Water', 1, 0, 'Raikou | Thundershock / Wild Charge\nZapdos | Charge Beam / Thunder Bolt\nJolteon | Thunder / Thunder Bolt', 'Electric, Grass', 'Fire, Water, Steel Ice', '**A/B** | Water Gun / Hydropump\n**B/A** | Water Gun / Aqua Tail\n**A/B** water Gun / Ice Beam\n', 0, 756, 0, 0, 0, 0),
    9: new Pokemon(9, 0x0902e5, 'Water', 4, 0, 'Zapdos | Charge Beam/(Thunderbolt, Zap Cannon)\nJolteon - Thunder Shock/Thunderbolt\n', 'Electric, Grass', 'Fire, Steel, Water, Ice', '**A/C** | Water Gun/Hydro Pump\n**A-/B-** | Bite/Hydro Pump\n**B/A-** | Water Gun/Ice Beam\n**B-/A** | Bite/Ice Beam\n**C/C-** | Water Gun/Flash Cannon\n**C/C-** | Bite/Flash Cannon', 0, 1309, 0, 0, 0, 0),
    10: undefined,
    11: undefined,
    12: undefined,
    13: undefined,
    14: undefined,
    15: undefined,
    16: undefined,
    17: undefined,
    18: undefined,
    19: undefined,
    20: undefined,
    21: undefined,
    22: undefined,
    23: undefined,
    24: undefined,
    25: undefined,
    26: undefined,
    27: undefined,
    28: undefined,
    28: new Pokemon(28, 0x966622, 'Ground', 2, 0, 'Exeggutor | Vine Whip/Solar Beam\nVenusaur | (Vine Whip, Razor Leaf)/Solar Beam\nVaporeon | Water Gun/Hydro Pump\nCloyster | Frost Breath/Avalanche', 'Grass, Water, Ice', 'Electric, Poison, Rock', '**A/A** | Metal Claw/Eathquake\n**A/B** | Mud Slap/ Earthquake\n**A/A** | Metal Claw/Bulldoze', 0, 1330, 0, 0, 0, 0),
    30: undefined,
    31: new Pokemon(31, 0xe064e0, 'Poison / Ground', 4, 0, 'Espeon | Confusion/Future Sight\nExeggutor | Confusion/Psychic\nAlakazam | Confusion/Future Sight\nGyarados | Waterfall/Hydro Pump\nVaporeon | Water Gun/Hydro Pump\nLugia | Extrasensory/Future Sight', 'Ground, Water, Psychic, Ice', 'Electric, Bug, Poison, Rock', '**A/A** | Poison Jab/Earthquake\n**A/B** | Poison Jab/Sludge Wave\n**B/C** | Poison Jab/Megahorn\n**B/A** | Iron Tail/Earthquake\n', 0, 1336, 0, 0, 0, 0),
    32: undefined,
    33: undefined,
    34: new Pokemon(34, 0xe064e0, 'Poison / Ground', 4, 0, 'Espeon | Confusion/Future Sight\nExeggutor | Confusion/Psychic\nAlakazam | Confusion/Future Sight\nGyarados | Waterfall/Hydro Pump\nVaporeon | Water Gun/Hydro Pump\nLugia | Extrasensory/Future Sight', 'Ground, Water, Pyschic, Ice', 'Electric, Bug, Poison, Rock', '**A/A** | Poison Jab/Earthquake\n**A/B** | Poison Jab/Sludge Wave\n**B/C** | Poison Jab/Megahorn\n**B/A** | Iron Tail/Earthquake\n', 0, 1363, 0, 0, 0, 0),
    35: undefined,
    36: undefined,
    37: undefined,
    38: new Pokemon(38, 0xff7b00, 'Fire', 3, 0, 'Omastar | (Rock Throw,Water Gun)/(Rock Blast, Hydropump,Rock Slide)\nVaporeon | Water Gun/(Aqua Tail, Hydropump)\n Golem | (Mud Slap,Mud Shot)/(Stone Edge, Rock Blast,Earthquake)', 'Water(X2), Ground(X2), Rock(X2))', 'Fire(X2), Grass(X2). Bug, Steel', '**A/A** | Fire Spin/Overheat\n**B/B** | Fire Spin/Solar Beam\n**B/C** | Feint Attack/Overheat\n**C/C** | Fire Spin/Heat Wave ', 0, 1233, 0, 0, 0, 0),
    39: undefined,
    40: undefined,
    41: undefined,
    42: undefined,
    43: undefined,
    44: undefined,
    45: undefined,
    46: undefined,
    47: undefined,
    48: undefined,
    49: undefined,
    50: undefined,
    51: undefined,
    52: undefined,
    53: undefined,
    54: undefined,
    55: undefined,
    56: undefined,
    57: undefined,
    58: undefined,
    59: new Pokemon(59, 0xff7b00, 'Fire', 3, 0, 'Rhydon | Mud Slap/(Stone Edge, Earthquake)\nGolem | (Mud Slap, Rock Throw, Mud Shot)/(Stone Edge, Earthquake)\nMewtwo | (Confusion, Psycho Cut)/(Shadow Ball, Psychic)', 'Rock, Ground, Water', 'Bug, Fire, Grass, Fairy, Steel, Ice', '**A/B** | Fire Fang/Fire Blast\n**B/A** | Fire Fang/Wild Charge\n**B/B** | Snarl/Fire Blast\n**B/A** | Snarl/Wild Charge\n**B/B** | Fire Fang/Crunch\n**C/B** | Snarl/Crunch', 0, 1622, 0, 0, 0, 0),
    60: undefined,
    61: undefined,
    62: new Pokemon(62, 0xa50000, 'Fighting / Water', 4, 0, 'Espeon | Confusion/Future Sight\nAlakazam | Confusion/Future Sight\nExeggutor | Confusion/Solar Beam\nRaikou | Thunder Shock/Wild Charge\nZapdos | Charge Beam/Thunderbolt\nJolteon | Thunder Shock/Thunderbolt\nMewtwo | Confusion/Psychic', 'Electric, Psychic, Grass, Fairy, Flying', 'Fire, Water, Ice, Fighting, Steel', '**A/A** | Bubble / Dynamic Punch\n**A/B** | Bubble / Hydropump\n**B/A** | Rock Smash / Dynamic Punch', 0, 1395, 0, 0, 0, 0),
    63: undefined,
    64: undefined,
    65: new Pokemon(65, 0xff494c, 'Psychic', 3, 0, 'Tyranitar | Bite/(Crunch, Stone Edge)\nScizor | Fury Cutter/X-Scissor\nPinsir | Fury Cutter/X-Scissor\nHoundoom | Snarl/Foul Play\nUmbreon | Snarl/Foul Play\nGengar | Hex/Shadow Ball', 'Bug, Dark, Ghost', 'Fighting, Psychic', '**A/F** | Psycho Cut/Future Sight\n**A/B** | Confusion/Future Sight\n**A-/D** | Psycho Cut/Shadow Ball\n**A-/A** | Confusion/Shadow Ball\n**C/F** | Psycho Cut/Focus Blast\n**C/B** | Confusion/Focus Blast', 0, 1649, 0, 0, 0, 0),
    66: undefined,
    67: undefined,
    68: new Pokemon(68, colors.fighting, 'Fighting', 3, 'Cloudy', '1. Mewtwo | Confusion / Psychic\n2. Rayquaza | Air Slash / Aerial Ace\n3. Lugia | Extrasensory / Sky Attack\n4. Gardevoir | Confussion / Dazzling Gleam\n5. Espeon | Confusion / Future Sight', 'Fairy, Flying, Psychic', 'Bug, Rock, Dark', '100%, 336, Counter / Dynamic Punch\n88.1%, 296, Counter / Heavy Slam\n82.1%, 276, Counter / *Submission\n80.4%, 270, Bullet Punch / Dynamic Punch\n77.4%, 260, *Karate Chop / Dynamic Punch\n76.2%, 256, Counter / *Cross Chop\n76.2%, 256, Counter / *Stone Edge\n76.2%, 256, Counter / Close Combat\n68.5%, 230, Bullet Punch / Heavy Slam\n65.5%, 220, *Karate Chop / Heavy Slam\nPlease see "More Info" for additional moveset ratings.\n* = Legacy Move', 1238, 1650, 2063, 2476, 2682, 2889),
    69: undefined,
    70: undefined,
    71: new Pokemon(71, 0x017208, 'Grass / Poison', 4, 0, 'Mewtwo | Confusion/Psychic\nMoltres | Fire Spin/Overheat\nEntei | Fire Spin/Overheat\nEspeon | Confusion/Future Sight\nAlakazam | Confusion/Future Sight\nEspeon| Confusion/Psychic', 'Fire, Psychic, Ice, Flying', 'Water, Fairy, Poison, Grass, Electric', '**A/A** | Razor Leaf/Solar Beam\n**A/A** | Acid/Solar Beam\n**B/A** | Razor Leaf/Leaf Blade\n**B/B** | Razor Leaf/Sludge Bomb', 0, 1296, 0, 0, 0, 0),
    72: undefined,
    73: new Pokemon(73, 0x0902e5, 'Water / Poison', 2, 0, 'Raikou | Thundershock / Wild Charge\nZapdos | Charge Beam / Thunderbolt\nAlakazam | (Psycho Cut, Confusion) / Future Sight', 'Grass, Ground, Electric, Psychic', 'Water, Poison, Steel, Fighting, Ice, Bug, Fire, Fairy', '**A/A** | Poison Jab / Hydropump\n**A/A** | Acid / Hydropump\n**A/B** |  Poison Jab / Blizzard', 0, 1356, 0, 0, 0, 0),
    74: undefined,
    75: undefined,
    76: new Pokemon(76, 0xba9560, 'Ground / Rock', 4, 0, 'Machamp | Counter/Close Combat\nVenusuar | Vine Whip/Solar Beam\nMachamp | Counter/ Dynamic Punch\nVaporeon | Water Gun/Hydropump', 'Grass(X2), Water(2)', 'Steel, Ground, Ice, Fighting', '**A/C** | Rock Throw/Stone Edge\n**A/B**  Rock Throw/Earthquake\n**B/C** | Rock Throw/Rock Blast\n**B/A** | Mud Slap/Stone Edge\n**B/A** | Mud Slap/Earthquake\n', 0, 1666, 0, 0, 0, 0),
    77: undefined,
    78: undefined,
    79: undefined,
    80: undefined,
    81: undefined,
    82: new Pokemon(82, 0xfff600, 'Electric / Steel', 2, 0, 'Rhydon | Mud Slap / Earthquake\nDonphan | Counter / Earthquake\nGolem | Mud Slap / Eathquake', 'Ground(X2),Fire, Fighting', 'Flying(X2), Poison(X2), Steel(X2)', '**A/C** | Thunder Shock / Discharge\n**A/B** | Spark / Discharge\n**B/C** | Spark / Zap Cannon', 0, 1278, 0, 0, 0, 0),
    83: undefined,
    84: undefined,
    85: undefined,
    86: undefined,
    87: undefined,
    88: undefined,
    89: new Pokemon(89, 0xe064e0, 'Poison', 2, 0, 'Mewtwo | (Confusion, Psycho Cut)/(Psychic, Shadow Ball)\nLugia | Extrasensory/Future Sight\nRhydon | Mud Slap/Earthquake\nGolem | (Mud Slap, Mud Shot)/Earthquake', 'Ground, Psychic', 'Bug, Grass, Fairy, Poison, Fight', '**A/A-** | Poison Jab/Gunk Shot\n**B/B** | Poison Jab/Sludge Wave\n**C/A-** | Infestation/Gunk Shot\n**C/A-** | Poison Jab/Dark Pulse\n**D/B** | Infestation/Sludge Wave\n**D/A** | Infestation/Dark Pulse', 0, 1548, 0, 0, 0, 0),
    90: undefined,
    91: new Pokemon(91, 0x509fd8, 'Ice / Water', 2, 0, 'Raikou | Thundershock / Wildcharge\nZapdos | Charge Beam / Thunder Bolt\nMachamp | Counter / (Dynamic/Close Combat)', 'Grass, Rock, Electric, Fighting', 'Ice, Water', '**A/B** | Frost Breath / Avalanche\n**A/A** | Ice Shard / Avalanche\n**A/C** | Frost Breath / Hydropump', 0, 1414, 0, 0, 0, 0),
    92: undefined,
    93: undefined,
    94: new Pokemon(94, colors.ghost, 'Ghost / Poison', 3, 'Cloudy, Fog', '1. Mewtwo | Confusion / Shadow Ball\n2. Groudon | Mud Shot / Earthquake\n3. Rayquaza | Air Slash | Outrage\n4. Tyranitar | Bite / Crunch\n5. Metagross | Zen Headbutt / Psychic', 'Dark, Ground, Ghost, Psychic', 'Bug (x2), Grass, Normal (x2), Fairy, Poison (x2), Fighting (x2)', '100%, 353, *Shadow Claw / Shadow Ball\n88.7%, 313, *Shadow Claw / *Dark Pulse\n88.7%, 313, *Shadow Claw / Sludge Bomb\n83.0, 293, *Shadow Claw / Focus Blast\n82.4%, 291, Sucker Punch / Shadow Ball\n76.5%, 270, Hex / Shadow Ball\n74.5%, 263, *Shadow Claw / *Sludge Wave\n71.1%, 251, Sucker Punch / *Dark Pulse\n71.1%, 251, Sucker Punch / Sludge Bomb\n65.4%, 231, Sucker Punch / Focus Blast\n65.2%, 230, Hex / *Dark Pulse\n65.2%, 230, Hex / Sludge Bomb\nPlease see "More Info" for additional moveset ratings.\n* = Legacy Move', 1122, 1496, 1870, 2245, 2432, 2619),
    95: undefined,
    96: undefined,
    97: undefined,
    98: undefined,
    99: undefined,
    100: undefined,
    101: undefined,
    102: undefined,
    103: new Pokemon(103, colors.grass, 'Grass / Psychic', 2, 'Clear / Sunny, Wind', '1. Scizor | Fury Cutter / X Scissor\n2. Entei | Fire Fang / Overheat\n3. Moltres | Fire Spin / Overheat\n4. Rayquaza | Air Slash / Aerial Ace\n5. Flareon | Fire Spin / Overheat', 'Bug (x2), Fire, Dark, Flying, Poison, Ghost, Ice', 'Electric, Grass, Ground, Fighting, Psychic, Water', '100%, 320, *Confusion / Solar Beam\n95.8%, 307, *Confusion / Seed Bomb\n93.8%, 300, *Zen Headbutt / Solar Beam\n90.0%, 288, Extrasensory / Solar Beam\n89.6%, 287, *Zen Headbutt / Seed Bomb\n85.8%, 275, Extrasensory / Seed Bomb\n76.3%, 244, Bullet Seed / Solar Beam\n75.0%, 240, *Confusion / Psychic\n72.1%, 231, Bullet Seed / Seed Bomb\n68.8%, 220, *Zen Headbutt / Pyschic\n65.0%, 208, Extrasensory / Psychic\n* = Legacy Move', 1250, 1666, 2083, 2500, 2708, 2916),
    104: undefined,
    105: new Pokemon(105, 0x966622, 'Ground', 2, 'Exggutor | Vine Whip, Solar Beam\nVenasaur | (Vine Whip,Razor Leaf)/Solar Beam\nArticuno | Frost Breath/(Blizzard,Ice Beam)', 'Grass, Water, Ice', 'Electric, Poison, Rock', '**A/B** | Mud Slap/Eathquake\n**A/A** | Mud Slap/ Dig\n**B/C** | Mud Slap/Bone Club', 0, 966, 0, 0, 0, 0),
    106: undefined,
    107: undefined,
    108: undefined,
    109: undefined,
    110: new Pokemon(110, 0xe064e0, 'Poison', 2, 0, 'Mewtwo | (Confusioin, Psycho Cut)/(Psychic, Shadow Ball)\nLugia | Extrasensory/Future Sight\nMoltres | Fire Spin/Overheat', 'Ground, Psychic', 'Bug, Grass, Fairy, Poison, Fight', '**B/A** | Infestation/Sludge Bomb\n**B/D** | Tackle/Sludge Bomb\n**C/A** | Infestation/Shadow Ball\n**C/D** | Tackle/Shadow Ball\n**D/D** | Tackle/Dark Pulse\n**D/B** | Infestation/Dark Pulse', 0, 1247, 0, 0, 0, 0),
    111: undefined,
    112: new Pokemon(112, 0x7F8290, 'Ground/Rock', 4, 0, 'Vaporeon | Water Gun/(Hydro Pump, Aqua Tail)\nMeganium | Razor Leaf/(Solar Beam, Petal Blizzard)\nPoliwrath | (Bubble, Rock Smash)/(Hydro Pump, Dynamic Punch)\nMachamp | (Counter, Karate Chop)/(Dynamic Punch, Close Combat, Cross Chop)', 'Grass (x2), Ground, Steel, Fight, Ice, Water (x2)', 'Electric (x2), Fire, Normal, Rock, Flying, Poison (x2)', '**A/C** - Frost Breath / Blizzard\n**A/B** - Frost Breath / Ice Beam\n**A-/F** - Water Gun / Hydro Pump\n**B/F** - Water Gun / Blizzard\n**B/D** - Water Gun / Ice Beam\n**B/C** - Frost Breath / Hydro Pump', 0, 1886, 0, 0, 0, 0),
    113: undefined,
    114: undefined,
    115: undefined,
    116: undefined,
    117: undefined,
    118: undefined,
    119: undefined,
    120: undefined,
    121: undefined,
    122: undefined,
    123: new Pokemon(123, 0x82f722, 'Bug / Flying', 3, 0, 'Golem | Rock Throw/Stone Edge\nOmastar | Rock Throw/Rock Slide\nMoltres | Fire Spin/Overheat\nEntei | Fire Spin/Overheat', 'Rock(X2), Electric, Fire, Ice', 'Ground, Grass, Fighting, Bug', '**A/B** | Air Slash/X-Scissor\n**A/F** | Fury Cutter/X-Scissor\n**A/A** | Air Slash/Arial Ace\n**A/D** | Fury Cutter/Arial Ace\n', 0, 1408, 0, 0, 0, 0),
    124: new Pokemon(124, colors.ice, 'Ice / Psychic', 3, 'Snow, Wind', '1. Entei | Fire Fang / Overheat\n2. Moltres | Fire Spin / Overheat\n3. Tyranitar | Bite / Crunch\n4. Mewtwo | Psycho Cut / Shadow Ball\n5. Flareon | Fire Spin / Overheat', 'Bug, Fire, Rock, Dark, Steel, Ghost', 'Ice, Psychic', '100%, 337, Confusion / Psyshock\n97.0%, 327, Frost Breath / Psyshock\n95.0%, 320, Confusion / Avalanche\n93.8%, 316, *Pound / Psyshock\n92.0%, 310, Frost Breath / Avalanche\n88.7%, 299, *Pound / Avalanche\n86.5%, 292, Confusion / *Ice Punch\n83.5%, 282, Frost Breath / *Ice Punch\n80.3%, 271, *Pound / Ice Punch\n77.2%, 260, Confusion / Draining Kiss\n74.2%, 250, Frost Breath / Draining Kiss\n70.9%, 239, *Pound / Draining Kiss\n* = Legacy Move', 1076, 1435, 1794, 2153, 2332, 2512),
    125: new Pokemon(125, 0xfff600, 'Electric', 2, 0, 'Rhydon | Mud Slap/Earthquake\nGolem | (Mud Slap, Mud Shot)/Earthquake\nMewtwo | (Confusion, Psycho Cut)/(Psychic, Shadow Ball)', 'Ground', 'Electric, Flying, Steel', '**A/B** | Thunder Shock/Thunderbolt\n**B/D** | Thunder Shock/Thunder\n**B/C** | Thunder Shock/Thunder Punch\n**B/A** | Low Kick/Thunderbolt\n**C/D** | Low Kick/Thunder\n**C/A** | Low Kick/Thunder Punch', 0, 1255, 0, 0, 0, 0),
    126: new Pokemon(126, 0xff7b00, 'Fire', 2, 0, 'Vaporeon | Water Gun/(Hyrdro Pump, Aqua Tail)\nMewtwo | (Confusion, Psycho Cut)/(Psychic, Shadow Ball)\nOmastar | (Rock Throw, Water Gun)/(Rock Slide, Hydro Pump, Rock Blast)', 'Rock, Ground, Water', 'Bug, Fire, Grass, Fairy, Steel, Ice', '**A/A** | Ember/Flamethrower\n**A/D** | Ember/Fire Blast\n**B/B** | Ember/Fire Punch\n**B/A** | Karate Chop/Flamethrower\n**B/B** | Karate Chop/Fire Punch\n**C/C** | Karate Chop/Fire Blast', 0, 1288, 0, 0, 0, 0),
    127: new Pokemon(127, colors.bug, 'Bug', 3, 'Rain', '1. Entei | Fire Spin / Overheat\n2. Moltres | Fire Spin / Overheat\n3. Rayquaza | Air Slash / Aerial Ace\n4. Flareon | Fire Spin \ Overheat\n5. Dragonite | Dragon Tail / Hurricane', 'Fire, Rock, Flying', 'Grass, Ground, Fighting', '100%, 286, Rock Smash / X Scissor\n94.3%, 270, Rock Smash / *Submission\n89.4%, 256, Rock Smash / Vice Grip\n87.3%, 250, Rock Smash / Close Combat\n77.3%, 221, Bug Bite / X Scissor\n71.6%, 205, Bug Bite / *Submission\n66.7%, 191, Bug Bite / Vice Grip\n65.4%, 187, *Fury Cutter / X Scissor\nPlease see "More Info" for additional moveset ratings.\n* = Legacy Move', 1187, 1583, 1978, 2374, 2572, 2770),
    128: undefined,
    129: new Pokemon(129, colors.water, 'Water', 1, 'Rain', '1. Raikou | Thunder Shock / Wild Charge\n2. Zapdos | Charge Beam / Thunder Bolt\n3. Ho-oh | Extrasensory / Solar Beam\n4. Mewtwo | Confusion / Shadow Ball\n5. Rayquaza | Dragon Tail / Outrage', 'Electric, Grass', 'Fire, Ice, Steel, Water', '100%, 106, Splash / Struggle', 94, 125, 157, 188, 204, 220),
    130: undefined,
    131: new Pokemon(131, 0x57A6D7, 'Ice/Water', 4, 0, 'Machamp | (Counter, Karate Chop)/(Dynamic Punch, Close Combat, Cross Chop)\nMewtwo | (Confusion, Psycho Cut)/(Focus Blast, Shadow Ball)\nZapdos | Charge Beam/(Thunderbolt, Zap Cannon)', 'Electric, Grass, Rock, Fight', 'Ice (x2), Water', '**A/C** | Frost Breath/Blizzard\n**A/B** | Frost Breath/Ice Beam\n**A-/F** | Water Gun/Hydro Pump\n**B/F** | Water Gun/Blizzard\n**B/D** | Water Gun/Ice Beam\n**B/C** | Frost Breath/Hydro Pump', 0, 1487, 0, 0, 0, 0),
    132: undefined,
    133: undefined,
    134: new Pokemon(134, 0x0902e5, 'Water', 3, 0, 'Zapdos | Charge Beam/(Thunderbolt, Zap Cannon)\nExeggutor | (Bullet Seed, Confusion, Extrasensory)/(Solar Beam, Seed Bomb)\nMewtwo | (Confusion, Psycho Cut)/(Psychic, Shadow Ball)', 'Electric, Grass', 'Fire, Steel, Ice, Water', '**A/A** | Water Gun/Hydro Pump\n**A-/A-** | Water Gun/Aqua Tail\n**B/B** | Water Gun/Water Pulse', 0, 1804, 0, 0, 0, 0),
    135: new Pokemon(135, 0xfff600, 'Electric', 3, 0, 'Rhydon | Mud Slap/Earthquake\nGolem | (Mud Slap, Mud Shot)/Earthquake\nDonphan | Counter/Earthquake', 'Ground', 'Electric, Flying, Steel', '**A/D** | Thunder Shock/Thunderbolt\n**A-/D** | Thunder Shock/Discharge\n**A-/F** | Thunder Shock/Thunder\n**B/A-** | Volt Switch/Thunderbolt\n**B/A** | Volt Switch/Discharge\n**C/B** | Volt Switch/Thunder', 0, 1560, 0, 0, 0, 0),
    136: new Pokemon(136, 0xff7b00, 'Fire', 3, 0, 'Omastar | (Water Gun, Rock Throw)/(Hydro Pump, Rock Slide, Rock Blast)\nMewtwo | (Confusion, Psycho Cut)/(Psychic, Shadow Ball)\nGolem | (Mud Slap, Rock Throw, Mud Shot)/(Stone Edge, Earthquake)', 'Rock, Ground, Water', 'Bug, Fire, Grass, Fairy, Steel, Ice', '**A/B** | Fire Spin/Overheat\n**A-/C** | Fire Spin/Fire Blast\n**A-/A** | Fire Spin/Flamethrower\n**B/C** | Ember/Overheat\n**B/C** | Ember/Fire Blast\n**B/B** | Ember/Flamethrower', 0, 1659, 0, 0, 0, 0),
    137: new Pokemon(137, 0x80847d, 'Normal', 3, 0, 'Machamp | Counter/Dynamic Punch\nHeracross | Counter/Close Combat\nPoliwrath | Rock Smash/Dynamic Punch\nMewtwo | Confusion/Focus Blast', 'Fighting', 'Ghost, Steel. Rock', '**A/A** | Hidden Power/Hyper Beam\n**A/B** | Charge Beam/Hyper Beam\n**B/B** | Hidden Power/Solar Beam\n', 0, 895, 0, 0, 0, 0),
    138: undefined,
    139: new Pokemon(139, 0xba9560, 'Rock / Water', 3, 0, 'Exeggutor | Bullet Seed/ Solar Beam\nVictreebel | Razor Leaf/Leaf Blade\nVenusaur | Vine Whip/Solar Beam\nMachamp | Counter/Dynamic Punch', 'Grass(X2), Ground, Electric, Fighting', 'Fire(X2), Normal, Ice, Poison, Flying', '**A/C** | Water Gun/Hydropump\n**B/B** | Mud Shot/Hydropump\n**B/C** | Water Gun/Rock Blast\n**B/B** | Water Gun/Ancient Power\n', 0, 1534, 0, 0, 0, 0),
    140: undefined,
    141: undefined,
    142: undefined,
    143: new Pokemon(143, 0x2F6C88, 'Normal', 4, 0, 'Machamp | Counter/Dynamic Punch\nHariyama | Counter/Dynamic Punch\nBreloom | Counter/Dynamic Punch\nTyranitar | Bite/Stone Edge\nUrsaring | Counter/Close Combat\nPoliwrath | Rock Smash/Dynamic Punch', 'Fighting', 'Ghost (x2)', '**A/B-** | Lick/Hyper Beam\n**B/B** | Zen Headbutt/Hyper Beam\n**C/B** | Lick/Heavy Slam\n**C/A** | Zen Headbutt/Heavy Slam\n**D/D** | Lick/Earthquake\n**D/C** | Zen Headbutt/Earthquake', 0, 1917, 0, 0, 0, 0),
    144: new Pokemon(144, 0x509fd8, "Flying/Ice", 5, 0, "Omastar | Rock Throw/(Rock Slide, Rock Blast)", "Rock (x2), Electric, Fire, Steel", "Ground (x2), Bug, Grass", "**A** | Frost Breath/Blizzard\n**A** | Frost Breath/Ice Beam\n**C** | Frost Breath/Icy Wind", 0, 1676, 0, 0, 0, 0),
    145: new Pokemon(145, 0xfff600, "Flying/Electric", 5, 0, "Golem | Rock Throw/(Stone Edge, Rock Blast)", "Rock, Ice", "Bug, Grass, Flying, Ground, Steel, Fight", "**A** | Charge Beam/Thunderbolt\n**A-** | Charge Beam/Zap Cannon\n**B** | Charge Beam/Thunder", 0, 1902, 0, 0, 0, 0),
    146: new Pokemon(146, 0xff7b00, "Flying/Fire", 5, 0, "Golem | Rock Throw/(Stone Edge, Rock Blast)\nOmastar | (Rock Throw, Water Gun)/(Rock Slide, Rock Blast, Hydro Pump)", "Electric, Rock (x2), Water", "Bug (x2), Fire, Grass (x2), Fairy, Ground, Steel, Fight", "**A** | Fire Spin/Overheat\n**B** | Fire Spin/Fire Blast\n**C** | Fire Spin/Heat Wave", 0, 1870, 0, 0, 0, 0),
    147: undefined,
    148: undefined,
    149: undefined,
    150: new Pokemon(150, colors.psychic, 'Psychic', 'EX Invite Only', 'Wind', '1. Mewtwo | Confusion / Shadow Ball\n2. Rayquaza | Dragon Tail / Outrage\n3. Tyranitar | Bit / Crunch\n4. Gyarados | Waterfall / Crunch\n5. Dragonite | Dragon Tail / Outrage', "Bug, Dark, Ghost", "Fighting, Psychic", "100%, 340, Confusion / Shadow Ball\n85.3%, 290, Confusion / Hyper Beam\n82.4%, 280, Confusion / Focus Blast\n77.9%, 265, Pyshco Cut / Shadow Ball\n70.6%, 240, Confusion / Pyschic\n63.2%, 215, Pyscho Cut / Hyper Beam\n60.3%, 205, Pyscho Cut / Focus Blast\n48.5%, 165, Pyscho Cut / Pyschic", 1706, 2275, 2844, 3413, 3698, 3982),
    151: undefined,
    152: undefined,
    153: new Pokemon(153, 0x017208, 'Grass', 1, 0, 'N/A', 'Bug, Fire, Flying, Poison, Ice', 'Electric, Grass, Ground, Water', 'Razor Leaf\nTackle\nEnergy Ball\nGrass Knot\nAncient Power', 0, 740, 0, 0, 0, 0),
    154: undefined,
    155: undefined,
    156: new Pokemon(156, 0xff7b00, 'Fire', 1, 0, 'N/A', 'Rock, Ground, Water', 'Bug, Fire, Grass, Fairy, Steel, Ice', 'Ember\nTackle\nFlame Charge\nDig\nFlamethrower', 0, 847, 0, 0, 0, 0),
    157: undefined,
    158: undefined,
    159: new Pokemon(159, 0x0902e5, 'Water', 1, 0, 'N/A', 'Electric, Grass', 'Fire, Steel, Ice, Water', 'Water Gun\nScratch\nCrunch\nIce Punch\nWater Pulse', 0, 913, 0, 0, 0, 0),
    160: undefined,
    161: undefined,
    162: undefined,
    163: undefined,
    164: undefined,
    165: undefined,
    166: undefined,
    167: undefined,
    168: undefined,
    169: undefined,
    170: undefined,
    171: undefined,
    172: undefined,
    173: undefined,
    174: undefined,
    175: undefined,
    176: undefined,
    177: undefined,
    178: undefined,
    179: undefined,
    180: undefined,
    181: undefined,
    182: undefined,
    183: undefined,
    184: undefined,
    185: undefined,
    186: undefined,
    187: undefined,
    188: undefined,
    189: undefined,
    190: undefined,
    191: undefined,
    192: undefined,
    193: undefined,
    194: undefined,
    195: undefined,
    196: undefined,
    197: undefined,
    198: undefined,
    199: undefined,
    200: new Pokemon(200, colors.ghost, 'Ghost', 2, 'Fog', '1. Tyranitar | Bite / Crunch\n2. Mewtwo | Psycho Cut / Shadow Ball\n3. Houndoom | Snarl / Foul Play\n4. Rayquaza | Dragon Tail / Outrage\n5. Gengar | Sucker Punch / Shadow Ball', 'Dark, Ghost', 'Bug, Normal (x2), Poison, Fighting (x2)', '100%, 230, Hex / Dark Pulse\n97.4%, 224, Astonish / Dark Pulse\n96.3%, 222, Hex / Shadow Sneak\n96.3%, 222, Hex / Ominous Wind\n93.7%, 216, Astonish / Shadow Sneak\n93.7%, 216, Astonish / Ominous Wind', 763, 1018, 1272, 1527, 1654, 1781),
    201: undefined,
    202: undefined,
    203: undefined,
    204: undefined,
    205: undefined,
    206: undefined,
    207: undefined,
    208: undefined,
    209: undefined,
    210: new Pokemon(210, colors.fairy, 'Fairy', 3, 'Cloudy', '1. Victreebel | Acid / Sludge Bomb\n2. Gengar | Sucker Punch / Sludge Bomb\n3.Metagross |  Bullet Punch / Flash Cannon\n4. Entei | Fire Fang / Overheat\n5. Venusaur | Vine Whip / Sludge Bomb', 'Poison, Steel', 'Bug, Dark, Dragon, Fightin', '100%, 362, Bite / Crunch\n91.1%, 330, Bite / Play Rough\n88.4%, 320, Snarl / Crunch\n79.5%, 288, Snarl / Play Rough\n69.0%, 250, Bite / Close Combat\n57.4%, 208, Snarl / Close Combat', 1046, 1394, 1743, 2092, 2266, 2440),
    211: undefined,
    212: undefined,
    213: undefined,
    214: undefined,
    215: new Pokemon(215, colors.dark, 'Dark / Fairy', 2, 'Fog, Snow', '1. Hariyama | Counter / Dynamic Punch\n2. Machamp | Counter / Dynamic Punch\n3. Blaziken | Counter / Focus Blast\n4. Heracross | Counter / Close Combat\n5. Mewtwo | Psycho Cut / Focus Blast', 'Bug, Fairy, Fighting (x2), Fire, Rock, Steel', 'Dark, Ghost, Ice, Psychic (x2)', '100%, 300, Feint Attack / Avalanche\n96.0%, 288, Ice Shard / Avalanche\n90.5%, 272, Feint Attack / Ice Punch\n86.7%, 260, Feint Attack / Foul Play\n86.5%, 260, Ice Shard / Ice Punch\n82.7%, 248, Ice Shard / Foul Play', 800, 1067, 1334, 1601, 1734, 1868),
    216: undefined,
    217: undefined,
    218: undefined,
    219: undefined,
    220: undefined,
    221: new Pokemon(221, colors.ice, 'Ice, Ground', 3, 'Snow, Clear / Sunny', '1. Entei | Fire Spin / Overheat\n2. Kyogre | Waterfall / Hydro Pump\n3. Moltres | Fire Spin / Overheat\n4. Machamp | Counter / Dynamic Punch\n5. Hariyama | Counter / Dynmaic Punch', 'Fire, Grass, Steel, Fightin, Water', 'Electric, Poison', '100%, 288, Ice Shard / Avalanche\n93.1%, 268, Ice Shard / Bulldoze\n77.1%, 222, Powder Snow / Avalanche\n72.2%, 208, Ice Shard / Stone Edge\n70.1%, 202, Powder Snow / Bulldoze\n49.3%, 142, Powder Snow / Stone Edge', 979, 1305, 1631, 1958, 2121, 2284),
    222: undefined,
    223: undefined,
    224: undefined,
    225: undefined,
    226: undefined,
    227: undefined,
    228: undefined,
    229: new Pokemon(229, colors.dark, 'Dark / Fire', 4, 'Fog, Clear / Sunny', '1. Kyogre | Waterfall / Hydro Pump\n2. Vaporeon | Water Gun / Hydro Pump\n3. Hariyama | Counter / Dynamic Punch\n4. Machamp | Counter / Dynamic Punch\n5. Rayquaza | Dragon Tail / Outrage', 'Rock, Ground, Fighting, Water', 'Fire, Grass, Dark, Steel, Ghost, Ice, Pyschic x2', '100%, 355, Fire Fang / Crunch\n90.1%, 320, Snarl Crunch\n79.7%, 283, Fire Fang / Fire Blast\n79.7%, 283, Fire Fang / Foul Play\n69.8%, 248, Snarl / Fire Blast\n69.8%, 258, Snarl / Foul Play', 1084, 1445, 1806, 2168, 2348, 2529),
    230: undefined,
    231: undefined,
    232: undefined,
    233: undefined,
    234: undefined,
    235: undefined,
    236: undefined,
    237: undefined,
    238: undefined,
    239: undefined,
    240: undefined,
    241: undefined,
    242: undefined,
    243: new Pokemon(243, 0xF5CC54, "Electric", 5, 0, "Golem | (Mud Slap, Mud Shot, Rock Throw)/Earthquake\nRhydon | Mud Slap/Earthquake", "Ground", "Electric, Flying, Steel", "**A** | Thunder Shock/Wild Charge\n**A** | Volt Switch/Wild Charge\n**A-** | Thunder Shock/Thunderbolt\n**A-** | Volt Switch/Thunderbolt\n**B** | Thunder Shock/Thunder\n**B** | Volt Switch/Thunder", 0, 1913, 0, 0, 0, 0),
    244: new Pokemon(244, 0xff7b00, 'Fire', 5, 0, 'Omastar | (Rock Throw, Water Gun)/(Rock Slide, Rock Blast, Hydro Pump)\nVaporeon | Water Gun/(Aqua Tail, Hydro Pump)\nGolem | Mud Slap/Stone Edge, Mud Shot/Rock Blast, Rock Throw/Earthquake', 'Rock, Ground, Water', 'Bug, Fire, Grass, Fairy, Steel, Ice', '**A** | Fire Spin/Overheat\n**A-** | Fire Fang/Overheat\n**A-** | Fire Spin/Flamethrower\n**B** | Fire Fang/Flamethrower\n**B-** | Fire Spin/Fire Blast\n**C** | Fire Fang/Fire Blast', 0, 1930, 0, 0, 0, 0),
    245: new Pokemon(245, 0x0902e5, 'Water', 5, 0, 'Raikou | Thunder Shock/Wild Charge\nZapdos | Charge Beam/(Thunderbolt, Zap Cannon)\nExeggutor | (Confusion,Extrasensory, Bullet Seed)/(Solar Beam, Seed Bomb)', 'Electric, Grass', 'Fire, Steel, Ice, Water', '**A** | Hidden Power/Hydro Pump\n**A-** | Extrasensory/Hydro Pump\n**B** | Hidden Power/Bubble Beam\n**B-** | Extrasensory/Bubble Beam\n**B-** | Hidden Power/Water Pulse\n**C** | Extrasensory/Water Pulse', 0, 1613, 0, 0, 0, 0),
    246: undefined,
    247: undefined,
    248: new Pokemon(248, colors.dark, 'Dark / Rock', 4, 'Partly Cloudy, Fog', '1. Hariyama | Counter / Dynamic Punch\n2. Machamp | Counter / Dynamic Punch\n3. Poliwrath | Rock Smash / Dynamic Punch\n4. Heracross | Counter / Close Combat\n5. Breloom | Counter / Dynamic Punch', 'Bug, Grass, Fairy, Ground, Steel, Fight (x2), Water', 'Fire, Normal, Dark, Flying, Poison, Ghost, Psychic (x2)', '100%, 437, Iron Tail / Crunch\n83.5%, 365, Iron Tail / Fire Blast\n82.8%, 362, Bite / Crunch\n74.4%, 325, Iron Tail / Stone Edge\n66.3%, 290, Bite / Fire Blast\n57.2%, 250, Bite / Stone Edge', 1573, 2097, 2621, 3146, 3408, 3670),
    249: new Pokemon(249, 0xf1EEF7, "Flying/Psychic", 5, 0, "Mewtwo | (Confusion, Psycho Cut)/Shadow Ball\nTyranitar | Bite/(Stone Edge, Crunch)\nZapdos | Charge Beam/(Thunderbolt, Thunder)", "Electric, Rock, Dark, Ghost, Ice", "Grass, Ground (x2), Fight (x2), Psychic", "**A** | Extrasensory/Sky Attack\n**A** | Extrasensory/Future Sight\n**B** | Dragon Tail/Sky Attack\n**B** | Dragon Tail/Future Sight\n**C** | Extrasensory/Hydro Pump\n**C-** | Dragon Tail/Hydro Pump", 0, 2056, 0, 0, 0, 0),
    250: new Pokemon(250, 0xff7b00, 'Fire / Flying', 5, 0, 'Zapdos | Charge Beam / (Thunderbolt,Zap Cannon)\nOmastar | (Rock Throw,Water Gun) / (Rock Slide,Blast, Hydropump)\nGolem | Rock Throw / (Stone Edge,Rock Blast)', 'Rock(X2), Water,Electric', 'Fire, Ground, Fairy, Fight', '**A/C** | Steel Wing / Fire Blast\n**A/A** | Extrasensory / Fire Blast\n**A/C** | Steel Wing / Solar Beam', 0, 2222, 0, 0, 0, 0),
    251: new Pokemon(251, 0xff494c, 'Psychic / Grass', 5, 0, 'Scizor | (Furry Cutter, Bullet Punch) / X-Scissor\nMewtwo | (Confusion,Psycho Cut) / Shadow Ball\nMoltres | Firespin / Overheat', 'Bug(X2), Fire, Poison, Dark, Flying, Ice, Ghost', 'Electric, Grass, Water, Pyschic, Ground, Fighting', '**A/A** | Confusion / Hyper Beam\n**A/A** | Confusion / Pyschic\n**A/A** | Confusion / Dazzeling Gleam', 0, 1766, 0, 0, 0, 0),
    252: undefined,
    253: undefined,
    254: undefined,
    255: undefined,
    256: undefined,
    257: undefined,
    258: undefined,
    259: undefined,
    260: undefined,
    261: undefined,
    262: undefined,
    263: undefined,
    264: undefined,
    265: undefined,
    266: undefined,
    267: undefined,
    268: undefined,
    269: undefined,
    270: undefined,
    271: undefined,
    272: undefined,
    273: undefined,
    274: undefined,
    275: undefined,
    276: undefined,
    277: undefined,
    278: undefined,
    279: undefined,
    280: undefined,
    281: undefined,
    282: undefined,
    283: undefined,
    284: undefined,
    285: undefined,
    286: undefined,
    287: undefined,
    288: undefined,
    289: undefined,
    290: undefined,
    291: undefined,
    292: undefined,
    293: undefined,
    294: undefined,
    295: undefined,
    296: undefined,
    297: undefined,
    298: undefined,
    299: undefined,
    300: undefined,
    301: undefined,
    302: new Pokemon(302, colors.dark, 'Dark / Ghost', 2, 'Fog', '1. Rayquaza | Dragon Tail / Outrage\n2. Kyogre | Waterfall / Hydro Pump\n3. Groudon | Mud Shot / Solar Beam\n4. Raikou | Thunder Shock / Wild Charge\n5. Tyranitar | Bite / Stone Edge', 'Fairy', 'Fighting, Normal (x2), Poison, Psychic (x2)', '100%, 313, Shadow Claw / Power Gem\n97.3%, 305, Shadow Claw / Shadow Sneak\n93.6%, 293, Shadow Claw / Foul Play\n89.5%, 280, Feint Attack / Power Gem\n86.7%, 272, Feint Attack / Shadow Sneak\n83.1%, 260, Feint Attack / Foul Play', 559, 745, 932, 1118, 1211, 1305),
    303: new Pokemon(303, colors.steel, 'Steel / Fairy', 2, 'Snow, Cloudy', '1. Entei | Fire Fang / Overheat\n2. Moltres | Fire Spin / Overheat\n3. Flareon | Fire Spin / Overheat\n4. Groudon | Mud Shot / Earthquake\n5. Blaziken | Fire Spin / Overheat', 'Fire, Ground', 'Bug (x2), Dark, Dragon (x2), Fairy, Flying, Grass, Ice, Normal, Pyshic, Rock', '100%, 330, Bite / Rough Play\n81.8%, 270, Bite / Iron Head\n77.6%, 256, Bite / Vice Grip\n73.9%, 244, Astonish / Play Rough\n55.8%, 184, Astonish / Iron Head\n51.5%, 170, Astonish / Vice Grip', 636, 848, 1060, 1272, 1378, 1484),
    304: undefined,
    305: undefined,
    306: new Pokemon(306, colors.steel, 'Steel / Rock', 4, 'Snow, Partly Cloudy', '1. Hariyama | Counter / Dynamic Punch\n2. Machamp | Counter / Dynamic Punch\n3. Groudon | Mud Shot / Earthquake\n4. Rhydon | Mud Slap / Earthquake\n5. Heracross | Counter / Close Combat', 'Fighting (x2), Ground (x2), Water', 'Normal (x2), Fighting, Poison (x4), Flying (x2), Psychic, Bug, Rock, Dragon, Fairy', '100%, 365, Iron Tail / Heavy Slam\n89.0%, 325, Iron Tail / Thunder\n89.0%, 325, Iron Tail / Stone Edge\n87.7%, 320, Dragon Tail / Heavy Slam\n76.7%, 280, Dragon Tail / Thunder\n76.7%, 280, Dragon Tail / Stone Edge', 1287, 1716, 2145, 2175, 2789, 3004),
    307: undefined,
    308: undefined,
    309: undefined,
    310: undefined,
    311: undefined,
    312: undefined,
    313: undefined,
    314: undefined,
    315: undefined,
    316: undefined,
    317: undefined,
    318: undefined,
    319: undefined,
    320: new Pokemon(320, colors.water, 'Water', 1, 0, 'Exeggutor | Bullet Seed/Solar Beam\nJolteon | Thunder Shock/Thunderbolt\nVictreebel | Razor Leaf/Solar Beam\nVenusaur | Vine Whip/Solar Beam\nAmpharos | Charge Beam/Zap Cannon\nVileplume | Razor Leaf/Solar Beam', 'Electric, Grass', 'Fire, Water, Ice, Steel', '**A** | Water Gun/Water Pulse\n**A** | Water Gun/Heavy Slam\n**A** | Water Gun/Body Slam\n**C** | Splash/Water Pulse\n**D** | Splash/Heavy Slam\n**D** | Splash/Body Slam\n', 0, 814, 1017, 0, 0, 0),
    321: undefined,
    322: undefined,
    323: undefined,
    324: undefined,
    325: undefined,
    326: undefined,
    327: undefined,
    328: undefined,
    329: undefined,
    330: undefined,
    331: undefined,
    332: undefined,
    333: new Pokemon(333, colors.normal, 'Normal, Flying', 1, 'Partly Cloudy, Wind', '1. Raikou | Thunder Shock / Wild Charge\n2. Zapdos | Charge Beam / Thunderbolt\n3. Kyogre | Waterfall / Blizzard\n4. Jolteon | Thunder Shock / Thunderbolt\n5. Regirock | Rock Throw / Stone Edge', 'Electric, Ice, Rock', 'Bug, Ghost, Grass, Ground (x2)', '100%, 312, Peck / Disarming Voice\n89.7%, 280, Peck / Ice Beam\n88.5%, Astonish / Disarming Voice\n85.4%, 267, Peck / Aerial Ace\n78.2%, 244, Astonish / Ice Beam\n73.9%, 231, Astonish / Aerial Ace', 309, 412, 516, 619, 671, 722),
    334: undefined,
    335: undefined,
    336: undefined,
    337: undefined,
    338: undefined,
    339: undefined,
    340: undefined,
    341: undefined,
    342: undefined,
    343: undefined,
    344: undefined,
    345: undefined,
    346: undefined,
    347: undefined,
    348: undefined,
    349: undefined,
    350: undefined,
    351: undefined,
    352: undefined,
    353: new Pokemon(353, colors.ghost, 'Ghost', 1, 'Fog', '1. Tyranitar | Bite / Crunch\n2. Rayquaza | Dragon Tail / Outrage\n3. Houndoom | Snarl / Foul Play\n4. Mewtwo | Psycho Cut / Shadow Ball\n5. Entei | Fire Fang / Overheat', 'Dark, Ghost', 'Bug, Fighting (x2), Normal (x2), Poison', '100%, 272, Feint Attack / Ominous Wind\n100%, 272, Feint Attack / Shadow Sneak\n88.4%, 240, Feint Attack / Night Shade\n79.4%, 216, Astonish / Ominous Wind\n79.4%, 216, Astonish / Shadow Sneak\n67.8%, 184, Astonish / Night Shade', 374, 498, 623, 748, 810, 872),
    354: undefined,
    355: new Pokemon(355, colors.ghost, 'Ghost', 1, 'Fog', '1. Tyranitar | Bite / Crunch\n2. Houndoom | Snarl / Foul Play\n3. Mewtwo | Psycho Cut / Shadow Ball\n4. Kyogre | Waterfall / Hydro Pump\n5. Entei | Fire Spin / Overheat', 'Dark, Ghost', 'Bug, Fighting (x2), Normal (x2), Poison', '100%, 222, Hex / Ominous Wind\n100%, 222, Hex / Shadow Sneak\n97.3%, 216, Astonish / Ominous Wind\n97.3%, 216, Astonish / Shadow Sneak\n85.8%, 190, Hex / Night Shade\n83.1%, 184, Astonish / Night Shade', 224, 299, 374, 449, 486, 523),
    356: undefined,
    357: undefined,
    358: undefined,
    359: new Pokemon(359, colors.dark, 'Dark', 4, 'Fog', '1. Machamp | Counter / Dynamic Punch\n2. Hariyama | Bullet Punch / Dynamic Punch\n3. Rayquaza | Dragon Tail / Outrage\n4. Blaziken | Counter / Focus Blast\n5. Mewtwo | Psycho Cut / Focus Blast', 'Fighting(x2), Bug(x2), Fairy(x2)', 'Psychic(x2), Ghost, Dark', '100%, 268, Snarl / Dark Pulse\n84.0%, 225, Psycho Cut / Dark Pulse\n77.6%, 208, Snarl / Thunder\n73.9, 198, Snarl / Megahorn\n61.6%, 165, Psycho Cut / Thunder\n57.8%, 155, Psycho Cut / Megahorn', 977, 1303, 1629, 1955, 2117, 2280),
    360: undefined,
    361: new Pokemon(361, colors.ice, 'Ice', 1, 'Ice', '1. Entei | Fire Spin / Overheat\n2. Moltres | Fire Spin / Overheat\n3. Hariyama | Counter / Dynmaic Punch\n4. Flareon | Fire Spin / Overheat\n5. Mewtwo | Psycho Cut / Focus Blast', 'Fighting, Fire, Rock, Steel', 'Ice', '100%, 270, Hex / Shadow Ball\n93.3%, 252, Hex / Icy Wind\n92.6%, 250, Hex / Avalanche\n89.6$, 242, Powder Snow / Shadow Ball\n82.9%, 224, Powder Snow / Icy Wind\n82.2%, 222, Powder Snow / Avalanche', 331, 441, 551, 662, 717, 772),
    362: undefined,
    363: undefined,
    364: undefined,
    365: new Pokemon(365, colors.ice, 'Ice / Water', 4, 'Snow, Rain', '1. Zapdos | Charge Beam / Thunderbolts\n2. Raikou | Volt Switch / Wild Charge\n3. Mewtwo | Psycho Cut / Focus Blast\n4. Hariyama | Counter / Dynamic Punch\n5. Exeggutor | Bullet Seed / Solar Beam', 'Electric, Grass, Rock, Fighting', 'Ice (x2), Water', '100%, 348, Waterfall / Water Pulse\n97.1%, 338, Waterfall / Blizzard\n94.3%, 328, Waterfall / Earthquake\n77.6%, 270, Frost Breath / Water Pulse\n74.7, 260, Frost Breath / Blizzard\n71.8%, 250, Frost Breath / Earthquake', 1117, 1489, 1862, 2234, 2420, 2606),
    366: undefined,
    367: undefined,
    368: undefined,
    369: undefined,
    370: undefined,
    371: undefined,
    372: undefined,
    373: undefined,
    374: undefined,
    375: undefined,
    376: undefined,
    377: undefined,
    378: undefined,
    379: undefined,
    380: new Pokemon(380, colors.dragon, 'Dragon / Psychic', 5, 'Wind', '1. Rayquaza | Dragon Tail / Outrage\n2. Dragonite | Steel Wing / Outrage\n3. Mewtwo | Confusion / Shadow Ball\n4. Tyranitar | Iron Tail / Crunch\n5. Gyarados | Bite / Outrage', 'Bug, Dark, Fairy, Dragon, Ghost, Ice', 'Electric, Fire, Grass, Fighting, Psychic, Water', '100%, 302, Dragon Breath / Dragon Claw\n90.1%, 271, Zen Headbutt / Dragon Claw\n82.9%, 250, Dragon Breath / Psychic\n82.9%, 250, Dragon Breath / Thunder\n73.0%, 220, Zen Headbutt / Psychic\n73.0, 220, Zen Headbutt / Thunder', 1447, 1929, 2412, 2895, 3136, 3377),
    381: new Pokemon(381, colors.dragon, 'Dragon / Psychic', 5, 'Wind', '1. Rayquaza | Dragon Tail / Outrage\n2. Dragonite | Dragon Tail / Outrage\n3. Mewtwo | Confusion / Shadow Ball\n4. Salamence | Dragon Tail / Draco Meteor\n5. Gyarados | Bite / Outrage', 'Bug, Dark, Fairy, Dragon, Ghost, Ice', 'Electric, Fire, Grass, Fighting, Psychic, Water', '100%, 330, Dragon Breath / Solar Beam\n91.4%, 302, Dragon Claw / Dragon Breath\n90.9%, 300, Zen Headbutt / Solar Beam\n82.3%, 272, Zen Headbutt / Dragon Claw\n75.8%, 250, Dragon Breath / Psychic\n66.7, 220, Zen Headbutt / Psychic', 1562, 2082, 2603, 3124, 3384, 3644),
    382: new Pokemon(382, 0x0902e5, 'Water', 5, 0, 'Raikou | Thunder Shock/Wild Charge\nZapdos | Charge Beam/Thunderbolt\nJolteon | Thunder Shock/Thunderbolt\nSceptile | Bullet Seed/Leaf Blade\nExeggutor | Bullet Seed/Solar Beam\nVenusaur | Vine Whip/Solar Beam\nGroudon | Mud Shot/Solar Beam\nHo-Oh | Extrasensory/Solar Beam', 'Electric, Grass', 'Fire, Water, Ice, Steel', '**A/A-** | Waterfall/Hydro Pump\n**B/A** | Waterfall/Blizzard\n**C/C** | Waterfall/Thunder', 0, 2328, 0, 0, 0, 0),
    383: new Pokemon(383, 0x966622, 'Ground', 5, 0, 'Gyarados | Waterfall/Hydro Pump\nExeggutor | Bullet Seed/Solar Beam\nVaporeon | Water Gun/Hydro Pump\nVenusaur | Vine Whip/Solar Beam\nSceptile | Bullet Seed/Leaf Blade\nArticuno | Frost Breath/Ice Beam\nJynx | Frost Breath/Avalanche\n', 'Water(x2), Grass(x2), Ice(x2)', 'Electric(x2), Poison, Rock', '**A** | Mud Shot/Solar Beam\n**A-** | Mud Shot/Earthquake\n**A-** | Dragon Tail/Solar Beam\n**C** | Mud Shot/Fire Blast\n**C** | Dragon Tail/Earthquake', 0, 2328, 0, 0, 0, 0),
    384: new Pokemon(384, colors.dragon, 'Dragon / Flying', 5, 0, 'Articuno | Frost Breath/Ice Beam\nJynx | Frost Breath/Avalanche\nDragonite | Dragon Tail/Outrage\nKyogre | Waterfall/Blizzard\nSneasel | Ice Shard/Avalanche\nCloyster | Ice Shard/Avalanche\nPiloswine | Powder Snow/Avalanche\nLapras | Frost Breath/Ice Beam\nWalrein | Frost Breath/Blizzard\nTyranitar | Bite/Stone Edge\nGolem | Rock Throw/Stone Edge\nGardevoir | Confusion/Dazzling Gleam', 'Ice (x2), Rock, Dragon, Fairy', 'Fire, Water, Grass (x2), Fighting, Ground (x4), Bug', '**A** | Dragon Tail/Outrage\n**A** | Air Slash/Outrage\n**B** | Dragon Tail/Aerial Ace\n**B-** | Air Slash/Aerial Ace\n**C** | Dragon Tail/Ancient Power\n**C** | Air Slash/Ancient Power', 0, 2083, 2604, 0, 0, 0),
    385: undefined,
    386: undefined,
    387: undefined,
    388: undefined,
    389: undefined,
    390: undefined,
    391: undefined,
    392: undefined,
    393: undefined,
    394: undefined,
    395: undefined,
    396: undefined,
    397: undefined,
    398: undefined,
    399: undefined,
    400: undefined,
    401: undefined,
    402: undefined,
    403: undefined,
    404: undefined,
    405: undefined,
    406: undefined,
    407: undefined,
    408: undefined,
    409: undefined,
    410: undefined,
    411: undefined,
    412: undefined,
    413: undefined,
    414: undefined,
    415: undefined,
    416: undefined,
    417: undefined,
    418: undefined,
    419: undefined,
    420: undefined,
    421: undefined,
    422: undefined,
    423: undefined,
    424: undefined,
    425: undefined,
    426: undefined,
    427: undefined,
    428: undefined,
    429: undefined,
    430: undefined,
    431: undefined,
    432: undefined,
    433: undefined,
    434: undefined,
    435: undefined,
    436: undefined,
    437: undefined,
    438: undefined,
    439: undefined,
    440: undefined,
    441: undefined,
    442: undefined,
    443: undefined,
    444: undefined,
    445: undefined,
    446: undefined,
    447: undefined,
    448: undefined,
    449: undefined,
    450: undefined,
    451: undefined,
    452: undefined,
    453: undefined,
    454: undefined,
    455: undefined,
    456: undefined,
    457: undefined,
    458: undefined,
    459: undefined,
    460: undefined,
    461: undefined,
    462: undefined,
    463: undefined,
    464: undefined,
    465: undefined,
    466: undefined,
    467: undefined,
    468: undefined,
    469: undefined,
    470: undefined,
    471: undefined,
    472: undefined,
    473: undefined,
    474: undefined,
    475: undefined,
    476: undefined,
    477: undefined,
    478: undefined,
    479: undefined,
    480: undefined,
    481: undefined,
    482: undefined,
    483: undefined,
    484: undefined,
    485: undefined,
    486: undefined,
    487: undefined,
    488: undefined,
    489: undefined,
    490: undefined,
    491: undefined,
    492: undefined,
    493: undefined,
    494: undefined,
    495: undefined,
    496: undefined,
    497: undefined,
    498: undefined,
    499: undefined,
    500: undefined,
    501: undefined,
    502: undefined,
    503: undefined,
    504: undefined,
    505: undefined,
    506: undefined,
    507: undefined,
    508: undefined,
    509: undefined,
    510: undefined,
    511: undefined,
    512: undefined,
    513: undefined,
    514: undefined,
    515: undefined,
    516: undefined,
    517: undefined,
    518: undefined,
    519: undefined,
    520: undefined,
    521: undefined,
    522: undefined,
    523: undefined,
    524: undefined,
    525: undefined,
    526: undefined,
    527: undefined,
    528: undefined,
    529: undefined,
    530: undefined,
    531: undefined,
    532: undefined,
    533: undefined,
    534: undefined,
    535: undefined,
    536: undefined,
    537: undefined,
    538: undefined,
    539: undefined,
    540: undefined,
    541: undefined,
    542: undefined,
    543: undefined,
    544: undefined,
    545: undefined,
    546: undefined,
    547: undefined,
    548: undefined,
    549: undefined,
    550: undefined,
    551: undefined,
    552: undefined,
    553: undefined,
    554: undefined,
    555: undefined,
    556: undefined,
    557: undefined,
    558: undefined,
    559: undefined,
    560: undefined,
    561: undefined,
    562: undefined,
    563: undefined,
    564: undefined,
    565: undefined,
    566: undefined,
    567: undefined,
    568: undefined,
    569: undefined,
    570: undefined,
    571: undefined,
    572: undefined,
    573: undefined,
    574: undefined,
    575: undefined,
    576: undefined,
    577: undefined,
    578: undefined,
    579: undefined,
    580: undefined,
    581: undefined,
    582: undefined,
    583: undefined,
    584: undefined,
    585: undefined,
    586: undefined,
    587: undefined,
    588: undefined,
    589: undefined,
    590: undefined,
    591: undefined,
    592: undefined,
    593: undefined,
    594: undefined,
    595: undefined,
    596: undefined,
    597: undefined,
    598: undefined,
    599: undefined,
    600: undefined,
    601: undefined,
    602: undefined,
    603: undefined,
    604: undefined,
    605: undefined,
    606: undefined,
    607: undefined,
    608: new Pokemon(608, 0x9212e8, 'Psychic/Flying', 100, 'Niantic | Game Updates/John Hanke', 'Niantic Labs', 'http://madpogotracker.info', 'All moves are A+', '???', '???', '???', '???', '???', '???'),
    609: undefined,
    610: undefined,
    611: undefined,
    612: undefined,
    613: undefined,
    614: undefined,
    615: undefined,
    616: undefined,
    617: undefined,
    618: undefined,
    619: undefined,
    620: undefined,
    621: undefined,
    622: undefined,
    623: undefined,
    624: undefined,
    625: undefined,
    626: undefined,
    627: undefined,
    628: undefined,
    629: undefined,
    630: undefined,
    631: undefined,
    632: undefined,
    633: undefined,
    634: undefined,
    635: undefined,
    636: undefined,
    637: undefined,
    638: undefined,
    639: undefined,
    640: undefined,
    641: undefined,
    642: undefined,
    643: undefined,
    644: undefined,
    645: undefined,
    646: undefined,
    647: undefined,
    648: undefined,
    649: undefined,
    650: undefined,
    651: undefined,
    652: undefined,
    653: undefined,
    654: undefined,
    655: undefined,
    656: undefined,
    657: undefined,
    658: undefined,
    659: undefined,
    660: undefined,
    661: undefined,
    662: undefined,
    663: undefined,
    664: undefined,
    665: undefined,
    666: undefined,
    667: undefined,
    668: undefined,
    669: undefined,
    670: undefined,
    671: undefined,
    672: undefined,
    673: undefined,
    674: undefined,
    675: undefined,
    676: undefined,
    677: undefined,
    678: undefined,
    679: undefined,
    680: undefined,
    681: undefined,
    682: undefined,
    683: undefined,
    684: undefined,
    685: undefined,
    686: undefined,
    687: undefined,
    688: undefined,
    689: undefined,
    690: undefined,
    691: undefined,
    692: undefined,
    693: undefined,
    694: undefined,
    695: undefined,
    696: undefined,
    697: undefined,
    698: undefined,
    699: undefined,
    700: undefined,
    701: undefined,
    702: undefined,
    703: undefined,
    704: undefined,
    705: undefined,
    706: undefined,
    707: undefined,
    708: undefined,
    709: undefined,
    710: undefined,
    711: undefined,
    712: undefined,
    713: undefined,
    714: undefined,
    715: undefined,
    716: undefined,
    717: undefined,
    718: undefined,
    719: undefined,
    720: undefined,
    721: undefined,
    722: undefined,
    723: undefined,
    724: undefined,
    725: undefined,
    726: undefined,
    727: undefined,
    728: undefined,
    729: undefined,
    730: undefined,
    731: undefined,
    732: undefined,
    733: undefined,
    734: undefined,
    735: undefined,
    736: undefined,
    737: undefined,
    738: undefined,
    739: undefined,
    740: undefined,
    741: undefined,
    742: undefined,
    743: undefined,
    744: undefined,
    745: undefined,
    746: undefined,
    747: undefined,
    748: undefined,
    749: undefined,
    750: undefined,
    751: undefined,
    752: undefined,
    753: undefined,
    754: undefined,
    755: undefined,
    756: undefined,
    757: undefined,
    758: undefined,
    759: undefined,
    760: undefined,
    761: undefined,
    762: undefined,
    763: undefined,
    764: undefined,
    765: undefined,
    766: undefined,
    767: undefined,
    768: undefined,
    769: undefined,
    770: undefined,
    771: undefined,
    772: undefined,
    773: undefined,
    774: undefined,
    775: undefined,
    776: undefined,
    777: undefined,
    778: undefined,
    779: undefined,
    780: undefined,
    781: undefined,
    782: undefined,
    783: undefined,
    784: undefined,
    785: undefined,
    786: undefined,
    787: undefined,
    788: undefined,
    789: undefined,
    790: undefined,
    791: undefined,
    792: undefined,
    793: undefined,
    794: undefined,
    795: undefined,
    796: undefined,
    797: undefined,
    798: undefined,
    799: undefined,
    800: undefined,
    801: undefined,
    802: undefined,
    803: undefined
}


client.on('message', message => {
    // Help
    if (message.content.toLowerCase() === '?help') {
        message.author.createDM().then((dm) => { dm.send("Hi, thanks for using the automated Pokedex bot!\n\nI can provide quick information on different Pokemon types as well as specific Pokemon.\n\nFor information on Pokemon types, use commands `?type`, ie. `?water` will return important information on water type Pokemon.\n\nFor information on specific Pokemon, use commands `?pokemon` or `?pokemon id`, ie. `?articuno` and/or `?144` will both return important information on Articuno.") }).catch(console.error)
    }
    //only do something if it starts with a ? and doesn't come from self.
    else if (message.content.startsWith('?') && message.author.id != client.user.id) {
        console.log("Pokedex from " + message.author.username + ":\t" + message.content);

        //Is it a type?
        if (types[message.content.toLowerCase().substr(1)]) {
            message.reply({ embed: types[message.content.toLowerCase().substr(1)].emb })
        }
        else if (boostedType[message.content.substr(1)]) {
            message.reply({ embed: boostedType[message.content.toLowerCase().substr(1)].emb })
        }
        //nope. not a type.  Maybe a pokemon? 
        //let's find out what pokemon it is..
        else {
            let pokeID = interpretPoke(message.content.substr(1))
            if (pokemon[pokeID]) {
                message.reply({ embed: pokemon[pokeID].emb })
            }
            //Darned if I know what's going on. 
            else {
                message.author.createDM().then((dm) => { dm.send("Sorry, I couldn't understand your message.\n" + message.content) }).catch(console.error)
            }
        }
    }
});


client.login(pokedexToken);
